config/routes.rb
R2::Application.routes.draw do

  get 'repairs/new/:engine_id' => 'repairs#new'

  get 'repairs/engineArrived/:engine_id' => 'repairs#engineArrived'

  get 'repairs/repairOrder/:id'    => 'repairs#repairOrder'

  get 'repairs/repairStarted/:id'  => 'repairs#repairStarted'

  get 'repairs/repairFinished/:id' => 'repairs#repairFinished'

  get 'engines/index' => 'engines#index'

  get 'engineorders/engineInquiry' => 'engineorders#inquiry'

  get 'engineorders/engineInquiry/:id' => 'engineorders#inquiry', :as => :edit_inquery

  get 'engineorders/newInquiry/:engine_id' => 'engineorders#inquiry', :as => :new_inquiry

  get 'engineorders/engineOrdered/:id' => 'engineorders#ordered', :as => :ordered

  get 'engineorders/engineAllocated/:id' => 'engineorders#allocated', :as => :allocated

  get 'engineorders/engineShipped/:id' => 'engineorders#shipped', :as => :shipped

  get 'engineorders/engineReturning/:id' => 'engineorders#returning', :as => :returning


  resources :engineorders

  resources :arrivals

  resources :repairs

  root to: 'menu#show'

  devise_for :users
  
  resources :enginemodels

  resources :engines do
    get :autocomplete_engine_engine_model_name, :on => :collection
    collection { post :import }
  end

  resources :businessstatuses

  resources :enginestatuses

  resources :locations

  resources :companies do
    collection { post :import }
  end










end

app/models/engine.rb
# coding: utf-8
require 'engineorder'

class Engine < ActiveRecord::Base
  # config/initializers/constants.rb で一元的に定義した定数モジュールを取り込ん
  # でいます。
  # config/initializers/*.rb は、Rails アプリの起動時に自動で実行されるコードを
  # 置く場所です。
  # もちろん Engine に関する定数はここで定義することも可能ですが、今回はアプリ
  # 全体の定数を一ヶ所で一元管理したい、という要件があると想定してこの仕組みに
  # しました。
  include Constants::Engine

  # Association
  # engine.enginestatus は冗長に感じたので、DB スキーマを変更せずにアプリ内では
  # engine.status で Enginestatus をアクセスできるようにしてみました。
  belongs_to :status, class_name: 'Enginestatus', foreign_key: 'enginestatus_id'
  belongs_to :company

  has_many :repairs
  # 古いハッシュリテラルの書き方「:key => val」ではなく、Ruby 1.9 からの新記法
  # 「key: val」に統一しました。タイプ数も少ないですし。
  has_many :engineorders_as_new, class_name: 'Engineorder', foreign_key: 'new_engine_id'
  has_many :engineorders_as_old, class_name: 'Engineorder', foreign_key: 'old_engine_id'

  # Initialize Object
  after_initialize :initialize_engine

  # Validation
  validates :engine_model_name, presence: true
  validates :serialno, presence: true, uniqueness: { scope: :engine_model_name }

  # ActiveRecord のスコープ機能を使ってみました。
  # スコープは頻繁に使うクエリに名前を付けて便利に使いまわすための仕組みです。
  # 通常の where で作ったクエリにスコープで条件を追加したり、
  #   Engine.where(company: yes).suspended
  # ActiveRecord のアソシエーションに条件を追加したり、
  #   engine.engineorders_as_new.opened
  # といったことができます。
  #
  # スコープの中身にあたる、-> { where ... } は、Ruby 1.9 で追加された lambda
  # の新記法です。lambda { where ... } と同じ意味です。

  # サスペンド状態のエンジンのみを抽出するスコープ
  scope :suspended, -> { where suspended: true }
  # 修理済み状態のエンジンのみを抽出するスコープ
  scope :completed, -> { where status: Enginestatus.of_finished_repair }

  # 初期化
  def initialize_engine
    # ステータスが設定されていない場合は「整備前」にする。	
    status = Enginestatus.of_before_repair if enginestatus_id.nil?
  end
  
  # Get current repair (get unclosed one)
  # 現在作業中の整備オブジェクトを返す
  def current_repair
    # if このエンジンに関連する修理が 1 件以上ある場合
    #   foreach それぞれの修理について
    #     if 修理が仕掛かり中の場合
    #       return この修理を返却
    # else
    #   return nil
    #
    # というコードでしたが、上記は関連する修理について opened スコープによりク
    # エリを追加して先頭のレコードを取得するコードで書き換えられます。
    # コードが減り、かつ、DB からフェッチしたデータをアプリ側で精査することがな
    # くなるので、性能も上がるはずです。

    repairs.opened.first
  end

  # Get unclosed order (this engine is old engine for it and it is not unclosed)
  # 旧エンジンとして関わっている受注オブジェクトのうち、現在仕掛中のものを返す
  def current_order_as_old
    # 「現在仕掛中」の条件を含める場合は、下記のコメントアウトされたコードを使
    # うと、Engineorder の opened スコープが効くので「返却日 IS NULL」のレコー
    # ドだけに絞れます。

    #engineorders_as_old.opened.first
    engineorders_as_old.first
  end

  # Get unclosed order (this engine is new engine for it and it is not unclosed)
  # 新エンジンとして関わっている受注オブジェクトのうち、現在仕掛中のものを返す
  def current_order_as_new
    #engineorders_as_new.opened.first
    engineorders_as_new.first
  end

  # エンジン型式とシリアルNoを併せてエンジン名として表示する。
  def engine_name
    "#{engine_model_name} ( #{serialno} )"
  end

  # Engine.completedEngines クラスメソッドは、completed スコープを使って 
  #   Engine.completed
  # で取得できるので、削除しました。

  # サスペンド状態かどうか確認する。
  def suspended?
    return self.suspended
  end

  # サスペンド状態にする
  # 状態を変更するメソッドなので、わかりやすくするために ! で終わるメソッド名と
  # しました。
  # Ruby 界隈では、自分の状態を破壊的に更新するようなメソッドには ! を付ける慣
  # 習があります。
  def suspend!
    self.suspended = true
  end

  # サスペンド状態を解除する
  def release!
    self.suspended = false
  end

  # Engine#displaySuspend_orNot メソッドは、エンジンの状態をビューでどう表現す
  # るかという仕事をしてるようです。
  # モデルにビューの仕事が入り込むのはまずいので外に出しました。
  # 引越し先は、app/helpers/engines_helper.rb です。
  # app/helpers/*.rb は、ビューやコントローラで何度も使う便利メソッドを集める場
  # 所です。

  # Engine.start_year クラスメソッドは、定数 EARLIEST_START_YEAR として定義しま
  # した。

  # エンジンのステータスを設定するメソッドたちは、単純に engine.status = ... で
  # 状態を設定すれば十分と考え、削除しました。
  #
  # たとえば、
  #   engine.setBeforeArrive
  # は、
  #   engine.status = Enginestatus.of_before_arrive
  # といった具合になります。

  # 受領前状態かどうか？
  def before_arrive?
    # エンジン状態マスタの id を直接使うのではなく、エンジン状態オブジェクトで
    # 比較するようにしました。
    status == Enginestatus.of_before_arrive
  end

  # 整備前状態かどうか？
  def before_repair?
    status == Enginestatus.of_before_repair
  end

  # 整備中状態かどうか？
  def under_repair?
    status == Enginestatus.of_under_repair
  end

  # 整備完了(完成品)状態かどうか？
  def finished_repair?
    status == Enginestatus.of_finished_repair
  end

  # 出荷準備中状態かどうか？
  def before_shipping?
    #status == Enginestatus.of_before_shipping
    if status == Enginestatus.of_before_shipping
      return true
    else
      return false
    end
  end

  # 出荷済状態かどうか？
  def after_shipped?
    status == Enginestatus.of_after_shipped
  end

  # 廃却状態かどうか？
  def abolished?
    status == Enginestatus.of_abolished
  end

#エンジンのCSVをインポートする
def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    Engine.create! row.to_hash
  end
end



end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]

  autocomplete :engine, :engine_model_name, :full => true #, :extra_data => [:default_client_id, :default_client_name]
  
  # GET /engines
  # GET /engines.json
  def index
  
    # 1.初期表示（メニューなどからの遷移時）
    #    ログインユーザの会社コードのみを条件に抽出
    #    ①検索条件のクリア
    #    ②ログインユーザの会社コードという条件のみセッションへの保存
    # 2.検索ボタン押下時
    #    画面入力された条件に対して抽出
    #    ①検索条件のクリア
    #    ②画面入力された条件のセッションへの保存
    # 3.ページ繰り時
    #    直前の検索条件をもとにページ繰り
    #    ①検索条件のセッションからの取り出し
    if params[:page].nil?
      # ページ繰り以外
      @searched = Hash.new
      session[:searched] = @searched
      if params[:commit].nil?
        # 初期表示時：ログインユーザの部門コードという条件のみセッションへの保存
        # ハッシュのキーのような定型的な「識別子」っぽいものは、シンボルとした
        # 方が性能も可読性もあがると思いました。
        @searched[:company_id] = current_user.company_id
      else
        # 検索ボタン押下時：画面入力された条件のセッションへの保存
        # 検索条件を取り込むときに、あらかじめ blank? なものは設定されていない
        # と見なすように変更しました。
        params[:search].each do |key, val|
          @searched[key.intern] = val unless val.blank?
        end
      end
    else
      # ページ繰り時：検索条件のセッションからの取り出し
      @searched = session[:searched]
    end

    # Rails 標準の Arel 機能を使って、WHERE 条件をオブジェクトとして扱うように
    # 変更しました。
    # cond 配列に WHERE 条件を溜め込んでいきます。
    # Arel は SQL を組み立てるための DSL のようなもので、文字列として SQL 文の
    # 断片を埋め込む必要も無くなり、DBMS を取り替えやすくなります。
    arel = Engine.arel_table
    cond = []

    # 会社コード（管轄）
    if company_id = @searched[:company_id]
      cond.push(arel[:company_id].eq company_id)
    end
    # エンジン型式
    if engine_model_name = @searched[:engine_model_name]
      cond.push(arel[:engine_model_name].matches "%#{engine_model_name}%")
    end
    # お客様名
    if serialno = @searched[:serialno]
      cond.push(arel[:serialno].matches "%#{serialno}%")
    end
    # ステータス
    if enginestatus_id = @searched[:enginestatus_id]
      cond.push(arel[:enginestatus_id].eq enginestatus_id)
    end

    # cond 配列に溜め込んだ WHERE 条件を AND でつないで検索を実行しています。
    # cond.reduce(&:and) は、Ruby 1.9 で追加された、シンボルから Proc オブジェ
    # クトを作り出す構文を使っています。
    # cond.reduce { |result, c| result.and c } と同じ意味となります。
    # order 指定を paginate の引数で指定すると、実行時に will_paginate 内で
    # deprecated 警告が出たので、外に出しました。
#    @engines = Engine.where(cond.reduce(&:and)).order(:id).paginate(page: params[:page], per_page: 10)
    @engines = Engine.where(cond.reduce(&:and)).order(:updated_at).reverse_order.paginate(page: params[:page], per_page: 10)

  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: t('controller_msg.engine_created') }
        format.json { render action: 'show', status: :created, location: @engine }
      else
        format.html { render action: 'new' }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: t('controller_msg.engine_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url }
      format.json { head :no_content }
    end
  end

  #インポートする
  def import
    Engine.import(params[:file])
    redirect_to action: "index", notice: t("controller_meg.engine_imported")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engine_params
      params.require(:engine).permit(:engine_model_name, :serialno, :company_id, :enginestatus_id, :suspended, :page)
    end
end

app/helpers/engines_helper.rb
# coding: utf-8
module EnginesHelper
  # Engine#displaySuspend_orNot を、このヘルパークラスに移動しました。
  def display_suspended_or_not(engine)
    if engine.suspended?
      "<b>***サスペンド中***</b>".html_safe
    else
      ""
    end
  end
end

app/views/engines/_form.html.erb
<%= form_for(@engine) do |f| %>

  <%= render "errormsg" , modeldata: @engine %>

  <div class="field">
    <%= f.label :engine_model_name %><br>
    <%= autocomplete_field :engine, :engine_model_name, autocomplete_engine_engine_model_name_engines_path %>
  </div>
  <div class="field">
    <%= f.label :serialno %><br>
    <%= f.text_field :serialno %>
  </div>

  <% if current_user.yesOffice? %>
    <div>
      <%= f.label :company %><br>
      <%= f.collection_select( :company_id, Company.all, :id, :name, :include_blank => false ) %><br>	<br>
      <%= f.label :suspended %><br>
      <%= f.check_box :suspended %><br>
    </div>
  <% else %>
    <% if @engine.company_id.nil? %>
      <% engine_company_id = current_user.company_id %>
    <% else %> 
      <% engine_company_id = @engine.company_id %>
    <% end %>
      <%= f.hidden_field(:company_id, :value => engine_company_id) %><br>
  <% end %>

  <div><%= f.label :status %><br>
    <%= f.collection_select( :enginestatus_id, Enginestatus.all, :id, :name, :include_blank => false ) %><br><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>エンジン情報 修正</h1>

<%= render 'form' %>

<%= link_to t('views.link_show'), @engine %> |
<%= link_to t('views.link_back'), engines_path %>

app/views/engines/index.html.erb
<h1 class="title">エンジン一覧</h1>

<h3>検索条件</h3>
<%= form_tag engines_index_path, :method => :get do %>
<div class="well">
  <table>
    <% if current_user.yesOffice? %>
      <tr>
        <td width="80" >管轄     </td>
        <td width="120"><%= collection_select(:search, :company_id, Company.all, :id, :name, :include_blank => true, :selected => @searched[:company_id]) %></td>
      </tr>
    <% else %>
      <%= hidden_field(:search, :company_id, :value => current_user.company_id) %>
    <% end %>
    <tr>
      <td width="80" >エンジン型式</td>
      <td width="120"><%= text_field :search, :engine_model_name, :value => @searched[:engine_model_name] %><br /></td>
      <td width="80" >エンジンNo.</td>
      <td width="120"><%= text_field :search, :serialno, :value => @searched[:serialno] %><br /></td>
    </tr>
    <tr>
      <td width="80" >ステータス     </td>
      <td width="120"><%= collection_select(:search, :enginestatus_id, Enginestatus.all, :id, :name, :include_blank => true, :selected => @searched[:enginestatus_id]) %></td>
    </tr>
</table>

<%= submit_tag "検索" %>
<% end %>
</div>

<br />

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ステータス</th>      
      <th>エンジン型式</th>
      <th>エンジンNo.</th>
      <% if current_user.yesOffice? %>
        <th>管轄</th>
      <% end %>
      <th>返却日</th>
      <th>受領日</th>
      <th>サスペンド</th>
    </tr>
  </thead>

  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.status.name %></td>
        <td><%= engine.engine_model_name	 %></td>
        <td><%= engine.serialno %></td>
        <% if current_user.yesOffice? %>
          <td><%= engine.company.name unless engine.company.blank? %></td>
        <% end %>
        <td><%= engine.current_order_as_old.returning_date unless engine.current_order_as_old.nil? %></td>
        <td><%= engine.current_repair.arrive_date unless engine.current_repair.nil? %></td>
        <td><%= display_suspended_or_not(engine) %></td>

       <% unless current_user.tender? %>
        <td>
          <%= link_to '引合登録', new_inquiry_path(engine) %>
        </td>
          <% end %>
        <td><%= link_to '受領登録', engine_arrived_path(engine) %></td>
          <% if  engine.before_shipping?  %>
           <td>
            <%= link_to '出荷', shipped_path(engine.current_order_as_new) %>
           </td>
            <% end %>
      　　<% if current_user.yesOffice? %>
        　　<td><%= link_to '詳細', engine %></td>
        　　<td><%= link_to '修正', edit_engine_path(engine) %></td>
        　　<td><%= link_to '削除', engine, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
     　　 <% end %>  
      　　</tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @engines, :previous_label=>'≪前', :next_label=>'次≫' %>
<br>

<% if current_user.yesOffice? %>
  <hr>
    <%= form_tag import_engines_path, multipart: true do %>
      <%= file_field_tag :file %>
      <br>
      <%= submit_tag "インポート" %>
    <% end %>
  <br>
<% end %>


<%= link_to '新規登録', new_engine_path %>

app/views/engines/new.html.erb
<h1>エンジン 新規登録</h1>

<%= render 'form' %>

<%= link_to t('views.link_back'), engines_path %>

app/views/engines/show.html.erb
  <div class="field">
      <% if @engine.suspended %>
         ******サスペンド中******
      <% end %>
   </div>

  <div class="field">
  <%= Engine.human_attribute_name('engine_model_name') %>
  <%= @engine.engine_model_name %>
  </div>

  <div class="field">
    <%= Engine.human_attribute_name('serialno') %>
  <%= @engine.serialno %>
  </div>

<% if current_user.yesOffice? %>
  <div class="field">
    <%= Engine.human_attribute_name('company') %>
  <%= @engine.company.name %>
</div>
<% end %>

  <div class="field">
    <%= Engine.human_attribute_name('status') %>
    <%= @engine.status.name %>
  </div>


<% if current_user.yesOffice? %>
  <%= link_to t('views.link_edit'), edit_engine_path(@engine) %> |
<% end %>
<%= link_to t('views.link_back'), engines_path %>