config/routes.rb
R2::Application.routes.draw do

  get 'repairs/new/:engine_id' => 'repairs#new'

  get 'repairs/engineArrived/:engine_id' => 'repairs#engineArrived'

  get 'repairs/repairOrder/:id'    => 'repairs#repairOrder'

  get 'repairs/repairStarted/:id'  => 'repairs#repairStarted'

  get 'repairs/repairFinished/:id' => 'repairs#repairFinished'

  get 'engines/index' => 'engines#index'

  get 'engineorders/engineInquiry' => 'engineorders#inquiry'

  get 'engineorders/engineInquiry/:id' => 'engineorders#inquiry', :as => :edit_inquery

  get 'engineorders/newInquiry/:engine_id' => 'engineorders#inquiry', :as => :new_inquiry

  get 'engineorders/engineOrdered/:id' => 'engineorders#ordered', :as => :ordered

  get 'engineorders/engineAllocated/:id' => 'engineorders#allocated', :as => :allocated

  get 'engineorders/engineShipped/:id' => 'engineorders#shipped', :as => :shipped

  get 'engineorders/engineReturning/:id' => 'engineorders#returning', :as => :returning


  resources :engineorders

  resources :arrivals

  resources :repairs

  root to: 'menu#show'

  devise_for :users
  
  resources :enginemodels

  resources :engines do
    get :autocomplete_engine_engine_model_name, :on => :collection
    collection { post :import }
  end

  resources :businessstatuses

  resources :enginestatuses

  resources :locations

  resources :companies do
    collection { post :import }
  end










end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
  end
end

app/views/menu/show.html.erb
<h1>メインメニュー</h1>
<br>
<% if Engine.suspended.exists? %>
 <div class="alert alert-danger">サスペンド状態のエンジンがあります。</div>
<% end %>
<h3>業務</h3>
<p><%= link_to 'エンジン一覧', engines_path %></p>

<% unless current_user.tender? %>
  <p><%= link_to '流通情報一覧', engineorders_path %></p>
<% end %>
<p><%= link_to '整備一覧', repairs_path %></p>
<br>

<% unless current_user.tender? %>
 <h3>マスター管理</h3>
 <p><%= link_to '法人', companies_path %></p>
 <p><%= link_to 'エンジン型式', enginemodels_path %></p>
 <p><%= link_to 'ビジネスステータス', businessstatuses_path %></p>
 <p><%= link_to 'エンジンステータス', enginestatuses_path %></p>
 <br>
<% end %>
<h3>その他</h3>
<p><%= link_to 'プロファイル', edit_user_registration_path %></p>
<br>
<br>