config/routes.rb
R2::Application.routes.draw do

  get 'repairs/new/:engine_id' => 'repairs#new'

  get 'repairs/engineArrived/:engine_id' => 'repairs#engineArrived'

  get 'repairs/repairOrder/:id'    => 'repairs#repairOrder'

  get 'repairs/repairStarted/:id'  => 'repairs#repairStarted'

  get 'repairs/repairFinished/:id' => 'repairs#repairFinished'

  get 'engines/index' => 'engines#index'

  get 'engineorders/engineInquiry' => 'engineorders#inquiry'

  get 'engineorders/engineInquiry/:id' => 'engineorders#inquiry', :as => :edit_inquery

  get 'engineorders/newInquiry/:engine_id' => 'engineorders#inquiry', :as => :new_inquiry

  get 'engineorders/engineOrdered/:id' => 'engineorders#ordered', :as => :ordered

  get 'engineorders/engineAllocated/:id' => 'engineorders#allocated', :as => :allocated

  get 'engineorders/engineShipped/:id' => 'engineorders#shipped', :as => :shipped

  get 'engineorders/engineReturning/:id' => 'engineorders#returning', :as => :returning


  resources :engineorders

  resources :arrivals

  resources :repairs

  root to: 'menu#show'

  devise_for :users
  
  resources :enginemodels

  resources :engines do
    get :autocomplete_engine_engine_model_name, :on => :collection
    collection { post :import }
  end

  resources :businessstatuses

  resources :enginestatuses

  resources :locations

  resources :companies do
    collection { post :import }
  end










end

app/models/enginemodel.rb
class Enginemodel < ActiveRecord::Base
end

app/controllers/enginemodels_controller.rb
class EnginemodelsController < ApplicationController
  before_action :set_enginemodel, only: [:show, :edit, :update, :destroy]

  # GET /enginemodels
  # GET /enginemodels.json
  def index
    @enginemodels = Enginemodel.all
  end

  # GET /enginemodels/1
  # GET /enginemodels/1.json
  def show
  end

  # GET /enginemodels/new
  def new
    @enginemodel = Enginemodel.new
  end

  # GET /enginemodels/1/edit
  def edit
  end

  # POST /enginemodels
  # POST /enginemodels.json
  def create
    @enginemodel = Enginemodel.new(enginemodel_params)

    respond_to do |format|
      if @enginemodel.save
        format.html { redirect_to @enginemodel, notice: 'Enginemodel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @enginemodel }
      else
        format.html { render action: 'new' }
        format.json { render json: @enginemodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enginemodels/1
  # PATCH/PUT /enginemodels/1.json
  def update
    respond_to do |format|
      if @enginemodel.update(enginemodel_params)
        format.html { redirect_to @enginemodel, notice: 'Enginemodel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @enginemodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enginemodels/1
  # DELETE /enginemodels/1.json
  def destroy
    @enginemodel.destroy
    respond_to do |format|
      format.html { redirect_to enginemodels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enginemodel
      @enginemodel = Enginemodel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enginemodel_params
      params.require(:enginemodel).permit(:modelcode, :name)
    end
end

app/helpers/enginemodels_helper.rb
module EnginemodelsHelper
end

app/views/enginemodels/_form.html.erb
<%= form_for(@enginemodel) do |f| %>

  <%= render "errormsg" , modeldata: @enginemodel %>

  <div class="field">
    <%= f.label :modelcode %><br>
    <%= f.text_field :modelcode %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enginemodels/edit.html.erb
<h1>Editing enginemodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @enginemodel %> |
<%= link_to 'Back', enginemodels_path %>

app/views/enginemodels/index.html.erb
<h1>Listing enginemodels</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Modelcode</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @enginemodels.each do |enginemodel| %>
      <tr>
        <td><%= enginemodel.modelcode %></td>
        <td><%= enginemodel.name %></td>
        <td><%= link_to 'Show', enginemodel %></td>
        <td><%= link_to 'Edit', edit_enginemodel_path(enginemodel) %></td>
        <td><%= link_to 'Destroy', enginemodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enginemodel', new_enginemodel_path %>

app/views/enginemodels/new.html.erb
<h1>New enginemodel</h1>

<%= render 'form' %>

<%= link_to 'Back', enginemodels_path %>

app/views/enginemodels/show.html.erb
<p>
  <strong>Modelcode:</strong>
  <%= @enginemodel.modelcode %>
</p>

<p>
  <strong>Name:</strong>
  <%= @enginemodel.name %>
</p>

<%= link_to 'Edit', edit_enginemodel_path(@enginemodel) %> |
<%= link_to 'Back', enginemodels_path %>