config/routes.rb
R2::Application.routes.draw do

  get 'repairs/new/:engine_id' => 'repairs#new'

  get 'repairs/engineArrived/:engine_id' => 'repairs#engineArrived'

  get 'repairs/repairOrder/:id'    => 'repairs#repairOrder'

  get 'repairs/repairStarted/:id'  => 'repairs#repairStarted'

  get 'repairs/repairFinished/:id' => 'repairs#repairFinished'

  get 'engines/index' => 'engines#index'

  get 'engineorders/engineInquiry' => 'engineorders#inquiry'

  get 'engineorders/engineInquiry/:id' => 'engineorders#inquiry', :as => :edit_inquery

  get 'engineorders/newInquiry/:engine_id' => 'engineorders#inquiry', :as => :new_inquiry

  get 'engineorders/engineOrdered/:id' => 'engineorders#ordered', :as => :ordered

  get 'engineorders/engineAllocated/:id' => 'engineorders#allocated', :as => :allocated

  get 'engineorders/engineShipped/:id' => 'engineorders#shipped', :as => :shipped

  get 'engineorders/engineReturning/:id' => 'engineorders#returning', :as => :returning


  resources :engineorders

  resources :arrivals

  resources :repairs

  root to: 'menu#show'

  devise_for :users
  
  resources :enginemodels

  resources :engines do
    get :autocomplete_engine_engine_model_name, :on => :collection
    collection { post :import }
  end

  resources :businessstatuses

  resources :enginestatuses

  resources :locations

  resources :companies do
    collection { post :import }
  end










end

app/models/repair.rb
class Repair < ActiveRecord::Base

  # validation
  
  # Association
  belongs_to :engine
  
  # 作業中の整備のみを抽出するスコープ (出荷日が設定済みなら作業完了)
  # ActiveRecord のスコープ機能を使って、よく使う「作業中？」条件に名前を付けて
  # います。
  scope :opened, -> { where shipped_date: nil }

  # エンジンをセットする
  def setEngine(engine)
    if self.engine.nil?
      self.engine = engine
    else
      unless self.engine == engine
        prev_engine = self.engine
        prev_engine.suspend!
        prev_engine.save
        self.engine = engine
      end
    end
  end

  # getter and setter for virtual attribute
  # 返却日
  def returning_date
    unless self.engine.current_order_as_old.nil?
      return self.engine.current_order_as_old.returning_date
    end
    return nil
  end
  def returning_date=(returning_date_value)
    #新規作成時はself.engineがnilなので、いったん確認する。
    #(nilに対してcurrent_order_oldは確認できない…)
    unless self.engine.nil?
      unless self.engine.current_order_as_old.nil? 
        self.engine.current_order_as_old.returning_date = returning_date_value
      end
    end
  end

  # getter and setter for virtual attribute
  # 返却コメント
  def returning_comment
    unless self.engine.current_order_as_old.nil?
      return self.engine.current_order_as_old.returning_comment
    end
    return nil
  end
  def returning_comment=(returning_comment_value)
    #新規作成時はself.engineがnilなので、いったん確認する。
    #(nilに対してcurrent_order_oldは確認できない…)
    unless self.engine.nil?
      unless self.engine.current_order_as_old.nil? 
        self.engine.current_order_as_old.returning_comment = returning_comment_value
      end
    end
  end

  #コメント（交換理由）
  def change_comment
    unless self.engine.current_order_as_old.nil?
      return self.engine.current_order_as_old.change_comment
    end
    return nil
  end
  def change_comment=(change_comment_value)
    #新規作成時はself.engineがnilなので、いったん確認する。
    unless self.engine.nil?
      unless self.engine.current_order_as_old.nil? 
        self.engine.current_order_as_old.change_comment = change_comment_value
      end
    end
  end



  # opened? 問い合わせメソッドを削除しました。
  # DB からフェッチしたデータをアプリ内でふるいにかけることになるので、opened
  # スコープを使って DB 検索時に予め作業中のレコードのみに絞るように変更しまし
  # た。

  # 現時点での発行Noの生成(年月-枝番3桁)
  def self.createIssueNo
    issuedate = Date.today.strftime("%Y%m") 
    maxseq = self.where("issue_no like ?", issuedate + "%").max()
    issueseq = '001'

   unless maxseq.nil?
    issueseq = sprintf("%03d", maxseq.issue_no.split('-')[1].to_i + 1)
   end

    return issuedate + "-" + issueseq
  end


  #現時点での依頼Noの生成 (年月-枝番3桁)
  def self.createOrderNo
    orderdate = Date.today.strftime("%Y%m") 
    maxseq = self.where("order_no like ?", orderdate + "%").max()
    orderseq = '001'
    unless maxseq.nil?
      orderseq = sprintf("%03d", maxseq.order_no.split('-')[1].to_i + 1)
    end
    return orderdate + "-" + orderseq
  end
  
  
  #試運転日から運転年数を求める。(運転年数は、切り上げ)
  def calcRunningYear
    return  ((Date.today - self.day_of_test)/365).ceil unless self.day_of_test.nil? 
  end

end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all.order(:updated_at).reverse_order.paginate(page: params[:page], per_page: 10)
    #Yes本社の場合全件表示、それ以外の場合は自社の管轄のエンジンの整備依頼に対してのみ表示する。
    #※管轄が変わると表示されなくなるので注意が必要…
    #if current_user.yesOffice?
    #  @repairs = Repair.all.order(:updated_at).reverse_order.paginate(page: params[:page], per_page: 10)
    #else
    #  engines = Engine.where(company_id: current_user.company_id).pluck(:id)
    #  @repairs = Repair.where(engine_id: engines).order(:updated_at).reverse_order.paginate(page: params[:page], per_page: 10)
    #end
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
    # パラメータにengine_idがあり、整備にまだエンジンが紐づけられていなければ、エンジンを紐づける
    if !(params[:engine_id].nil?)
      if @repair.engine.nil?
        @repair.engine = Engine.find(params[:engine_id])
      end
    end
  end

  # GET /repairs/1/edit
  # ステータスでレンダリング先を変える。
  def edit
    #エンジンが受領前状態の場合、
    # メソッド名の lower-camel-case -> snake-case 変更です。
    # ここの if 文の並びも排他的な条件なので、case 文に変更すると読みやすくなる
    # と思います。
    if @repair.engine.before_arrive?
      render :templathe => "repairs/returning"
    end
    #エンジンが整備前状態の場合、整備前
    if @repair.engine.before_repair?
      render :template => "repairs/engineArrived"
    end
    #エンジンが整備中の場合
    if @repair.engine.under_repair?
      render :template => "repairs/repairStarted"
    end
    #エンジンが整備完了(完成品状態)の場合、
    if @repair.engine.finished_repair?
      render :template => "repairs/repairFinished"
    end
  
    #if @repair.engine.beforeShipping?
    #  render :template => "engineorders/?"
    #end
    #if @repair.engine.afterShipped?
    #  render :template => "engineorders/?"
    #end
  
  end

  # POST /repairs
  # POST /repairs.json
  def create
    # パラメータにエンジンIDがある場合、まずエンジンに、作業中の整備オブジェクトの取得を試みる
    engine = Engine.find(params[:repair][:engine_id])
    @reapir = engine.current_repair

    # 作業中の整備オブジェクトが存在しない場合、整備オブジェクトを作って、当該のエンジンに紐づける
    if @reapir.nil?
      @repair = Repair.new(repair_params)  
      @repair.issue_no = Repair.createIssueNo
      @repair.issue_date = Date.today
      @repair.engine = engine
    end

    # エンジンのステータスをセットする。
    setEngineStatus
    @repair.engine.save
    
    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: t("controller_msg.repair_created") }
        format.json { render action: 'show', status: :created, location: @repair }
      else
        format.html { render action: 'new' }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    #整備依頼の場合、新規に依頼Noと整備依頼日を取得する
      if params[:commit] == t('views.buttun_repairOrdered')
        @repair.order_no = Repair.createOrderNo
        @repair.order_date = Date.today
      end

    respond_to do |format|
      if @repair.update(repair_params)
        # パラメータにenginestatus_idがあれば、エンジンのステータスを設定し、所轄をログインユーザの会社に変更する
        self.setEngineStatus

		    #if !(params[:enginestatus_id].nil?)
		    #  @repair.engine.enginestatus = Enginestatus.find(params[:enginestatus_id].to_i)
		    #  if params[:enginestatus_id].to_i == 1
        #    @repair.engine.company = current_user.company
		    #  end
		    #end
		    
		    # もし整備依頼の場合は、その整備会社のユーザに整備依頼メールを送信する。
#
#		    if params[:commit] == t('views.buttun_repairOrdered')
#           R2mailer.sendRepairOrderMail(User.collect_emails_by_company(@repair.engine.company)  , @repair).deliver
#        end

		    @repair.engine.save
		    
        format.html { redirect_to @repair, notice: t("controller_msg.repair_updated") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url }
      format.json { head :no_content }
    end
  end

  # GET /repairs/engineArrived/1
  def engineArrived
    # パラメータにエンジンIDがある場合、まずエンジンに、作業中の整備オブジェクトの取得を試みる
    engine = Engine.find(params[:engine_id])
    @repair = engine.current_repair
    # 作業中の整備オブジェクトが存在しない場合、整備オブジェクトを作って、当該のエンジンに紐づける
    if @repair.nil?
      @repair = Repair.new()  
	    if !(params[:engine_id].nil?)
        @repair.engine = engine
	    end   
    end
  end

  # GET /repairs/repairStarted/1
  def repairStarted
    set_repair
  end

  # GET /repairs/repairFinished/1
  def repairFinished
    set_repair
  end
  
  # GET /repairs/repairOrder/1  
  def repairOrder
    set_repair
  end

  # 必要に応じて、エンジンのステータスと所轄を設定する
  def  setEngineStatus
  
    # 受領登録時→整備前
    if params[:commit] == t('views.buttun_arrived')
      # エンジンオブジェクトの状態更新を、そのまま代入文に置き換えました。
      @repair.engine.status = Enginestatus.of_before_repair
      @repair.engine.company = current_user.company	
    end
    # 整備開始→整備中
    if params[:commit] == t('views.buttun_repairStarted')
      @repair.engine.status = Enginestatus.of_under_repair
      @repair.engine.company = current_user.company
    end
    # 整備完了→完成品
    if params[:commit] == t('views.buttun_repairFinished')
      @repair.engine.status = Enginestatus.of_finished_repair
      @repair.engine.company = current_user.company
    end

  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:id, :issue_no, :issue_date, :arrive_date, :start_date, :finish_date, :before_comment, :after_comment, :time_of_running, :day_of_test, :returning_comment, :arrival_comment, :order_no, :order_date, :construction_no, :desirable_finish_date, :estimated_finish_date, :engine_id, :enginestatus_id, :shipped_date)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper

  # エンジン到着登録のためのパスを生成する  
  def engine_arrived_path(engine)
    return '/repairs/engineArrived/' + engine.id.to_s
  end

  # 整備依頼のためのパスを生成する
  def order_repair_path(repair)
    return '/repairs/repairOrder/' +  repair.id.to_s
  end
  
  # 整備開始登録のためのパスを生成する
  def start_repair_path(repair)
    return '/repairs/repairStarted/' +  repair.id.to_s
  end

  # 整備完了登録のためのパスを生成する
  def finish_repair_path(repair)
    return '/repairs/repairFinished/' +  repair.id.to_s
  end



#画面上の編集可否を返す（受領画面）
def getDisabled_EngineArrived
  #整備会社の場合
  if current_user.tender?
      return  {
        :time_of_running=>true,
        :day_of_test=>true,
        :returning_date=>true,
        :returning_comment=>true
      }
  else
    return {
        :time_of_running=>false,
        :day_of_test=>false,
        :returning_date=>false,
        :returning_comment=>false
      }
  end
end



#画面上の編集可否を返す（整備依頼画面）
def getDisabled_RepairOrder
  #整備会社の場合
  if current_user.tender?
      return  {
       :issue_no=>true,
       :issue_date=>true,
       :time_of_running=>true,
       :day_of_test=>true,
       :arrive_date=>true,
       :order_no=>true,
       :order_date=>true,
       :construction_no=>true,
       :desirable_finish_date=>true
      }
  else
    return {
       :issue_no =>  true,
       :issue_date =>  true,
       :time_of_running => false,
       :day_of_test => false,
       :arrive_date=>false,
       :order_no=>false,
       :order_date=>false,
       :construction_no=>false,
       :desirable_finish_date=>false
      }
  end
end

#画面で編集否かどうかを返す（整備開始画面）
def getDisabled_RepairStarted
  #整備会社の場合
  if current_user.tender?
      return  {
        :order_no=>true,
        :order_date=>true,
        :construction_no=>true,
        :desirable_finish_date=>true
      }
  else
    return {
        :order_no=>false,
        :order_date=>false,
        :construction_no=>false,
        :desirable_finish_date=>false
      }
  end
end


#画面で編集否かどうかを返す（整備完了画面）
def getDisabled_RepairFinished
  #整備会社の場合
  if current_user.tender?
      return  {
        :order_no=>true,
        :order_date=>true,
        :construction_no=>true,
        :desirable_finish_date=>true,
        :start_date=>true,
        :estimated_finish_date=>true,
        :before_comment=>true
      }
  else
    return {
        :order_no=>false,
        :order_date=>false,
        :construction_no=>false,
        :desirable_finish_date=>false,
        :start_date=>false,
        :estimated_finish_date=>false,
        :before_comment=>false
    }
  end
end

end

app/views/repairs/_engineInfo.html.erb
  <div class="field">
    エンジン型式 <br>
    <%= text_field_tag 'engine_model_name', @repair.engine.engine_model_name, :disabled=>'true' %><br>
    エンジンNo. <br>
    <%= text_field_tag 'serialno', @repair.engine.serialno, :disabled=>'true' %><br>
  </div>

app/views/repairs/edit.html.erb
<h1>整備情報 訂正</h1>

<%= render 'form' %>

<%= link_to t('views.link_show'), @repair %> |
<%= link_to t('views.link_back'), repairs_path %>

app/views/repairs/engineArrived.html.erb
<h1>受領</h1>

<%= form_for(@repair) do |f| %>

  <%= render "errormsg" , modeldata: @repair %>


<div class="row">
<div class="col-md-5">
  <%= render 'engineInfo' %>
  <% disabled_data = getDisabled_EngineArrived %>

<br>
  <div class="field">
    <%= f.label :arrive_date %><br>
    <%= f.date_select :arrive_date, :use_month_numbers => true %>
  </div>
  <div>
    <%= f.hidden_field :engine_id %>
  </div>  
  <div class="actions">
    <%= f.submit  :value => t('views.buttun_arrived') %>
  </div>
<%= link_to t('views.link_back'), repairs_path %>

</div>
<div class="well col-md-5">
  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :disabled=>true %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.date_select :order_date, :use_month_numbers => true, :disabled=>true,  :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :time_of_running %><br>
    <%= f.number_field :time_of_running, :disabled=>disabled_data[:time_of_running] %>
  </div>
  <div class="field">
    <%= f.label :day_of_test %><br>
    <%= f.date_select :day_of_test, :use_month_numbers => true, :include_blank => true, :start_year => Engine::EARLIEST_START_YEAR, :disabled => disabled_data[:day_of_test] %>
  </div>
  
  <div class="field">
    <%= label_tag t('views.label_runningyear') %><br>
    <%= @repair.calcRunningYear %>
  </div>

  <div class="field">
    <%= f.label :returning_date %><br>
    <%= f.date_select :returning_date, :include_blank => true, :disabled => disabled_data[:returning_date],
     :use_month_numbers => true %>
  </div>

  <div class="field">
    <%= f.label :returning_comment %><br>
    <%= f.text_area :returning_comment, :disabled=>disabled_data[:returning_comment] %>
  </div>
</div>
</div>
<% end %>

app/views/repairs/index.html.erb
<h1>整備作業一覧</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ステータス</th>
      <th>依頼No</th>
      <th>整備依頼日</th>
      <th>完成希望日</th>
      <th>整備開始日</th>
      <th>整備完了日</th>
      <!--
      <th>出荷日</th>
      -->
      <th>エンジン型式</th>
      <th>エンジンNo.</th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.engine.status.name %></td>
        <td><%= repair.order_no %></td>
        <td><%= repair.order_date %></td>
        <td><%= repair.desirable_finish_date %></td>
        <td><%= repair.start_date %></td>
        <td><%= repair.finish_date %></td>
        <!--
        <td><%= repair.shipped_date %></td>
        -->
        <td><%= repair.engine.engine_model_name %></td>
        <td><%= repair.engine.serialno %></td>
        <% if current_user.yes? %>
          <td>
            <%= link_to '依頼', order_repair_path(repair) %>
          </td>
        <% end %>
        <td><%= link_to '開始', start_repair_path(repair) %></td>
        <td><%= link_to '完了', finish_repair_path(repair) %></td>
     <% if repair.engine.before_shipping? %>
          <td>
            <%= link_to '出荷', shipped_path(repair.engine.current_order_as_new) %>
          </td>
        <% end %>

        <% if current_user.yesOffice? %>
          <td><%= link_to '詳細', repair %></td>
          <td><%= link_to '訂正', edit_repair_path(repair) %></td>
          <td><%= link_to '削除', repair, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @repairs, :previous_label=>'≪前', :next_label=>'次≫' %>
<br>

app/views/repairs/new.html.erb
<h1>到着登録</h1>

<%= render 'form' %>

<%= link_to t('views.link_back'), repairs_path %>

app/views/repairs/repairFinished.html.erb
<h1>整備完了</h1>

<%= form_for(@repair) do |f| %>
  <%= render "errormsg" , modeldata: @repair %>

<div class="row">
  <div class="col-md-4">
  <%= render 'engineInfo' %>
  <% disabled_data = getDisabled_RepairFinished %>

<br>

  <div class="field">
    <%= f.label :finish_date %><br>
    <%= f.date_select :finish_date, :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :after_comment %><br>
    <%= f.text_area :after_comment %>
  </div>
  <div class="actions">
    <%= f.submit  :value => t('views.buttun_repairFinished') %>
  </div>
<%= link_to t('views.link_back'), repairs_path %>
</div>
<div class="well col-md-8">
 <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :disabled=> true %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.text_field :order_date, :disabled=> true %>
  </div>
<% if false %>
  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :disabled=> disabled_data[:order_no] %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.text_field :order_date, :disabled=> disabled_data[:order_date] %>
  </div>
<% end %>
  <div class="field">
    <%= f.label :construction_no %><br>
    <%= f.text_field :construction_no, :disabled=> disabled_data[:construction_no] %>
  </div>
  <div class="field">
    <%= f.label :desirable_finish_date %><br>
    <%= f.date_select :desirable_finish_date, :use_month_numbers => true, :disabled=>disabled_data[:desirable_finish_date] %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, :use_month_numbers => true, :disabled=>disabled_data[:start_date] %>
  </div>
  <div class="field">
    <%= f.label :estimated_finish_date %><br>
    <%= f.date_select :estimated_finish_date, :use_month_numbers => true, :disabled=>disabled_data[:estimated_finish_date] %>
  </div>
  <div class="field">
    <%= f.label :before_comment %><br>
    <%= f.text_area :before_comment, :disabled=>disabled_data[:before_comment] %>
  </div>
  </div>
  </div>
<% end %>

app/views/repairs/repairOrder.html.erb
<h1>整備依頼</h1>

<%= form_for(@repair) do |f| %>
  <%= render "errormsg" , modeldata: @repair %>

  <%= render 'engineInfo' %>
  <% disabled_data = getDisabled_RepairOrder %>

<br>

  <div class="field">
    <%= f.label :time_of_running %><br>
    <%= f.number_field :time_of_running, :disabled => disabled_data[:time_of_running]  %>
  </div>
  <div class="field">
    <%= f.label :day_of_test %><br>
    <%= f.date_select :day_of_test, :include_blank => true, :use_month_numbers => true, :start_year => Engine::EARLIEST_START_YEAR, :disabled => disabled_data[:day_of_test] %>
  </div>
  
  <div class="field">
    <%= label_tag t('views.label_runningyear') %><br>
    <%= @repair.calcRunningYear %>
  </div>

  <div class="field">
    <%= label_tag 'コメント(交換理由)' %><br>
    <%= f.text_area :change_comment, :disabled=> true %>
  </div>

  <div class="field">
    <%= f.label :arrive_date %><br>
    <%=  f.date_select :arrive_date, :use_month_numbers => true, :disabled=>disabled_data[:arrive_date] %>
  </div>

  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :disabled=> true %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.text_field :order_date, :disabled=> true %>
  </div>

  <div class="field">
    <%= f.label :construction_no %><br>
    <%= f.text_field :construction_no, :disabled=>disabled_data[:construction_no] %>
  </div>
  <div class="field">
    <%= f.label :desirable_finish_date %><br>
    <%= f.date_select :desirable_finish_date, :use_month_numbers => true, :disabled=>disabled_data[:desirable_finish_date] %>
  </div>

  <% if current_user.yesOffice? %>
    <div class="actions">
      <%= f.submit  :value => t('views.buttun_repairOrdered') %>
    </div>
  <% end %>
<%= link_to t('views.link_back'), repairs_path %>

<% end %>

app/views/repairs/repairStarted.html.erb
<h1>整備開始</h1>

<%= form_for(@repair) do |f| %>

  <%= render "errormsg" , modeldata: @repair %>


<div class="row">
  <div class="col-md-4">
  <%= render 'engineInfo' %>
  <% disabled_data = getDisabled_RepairStarted %>
<br>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :estimated_finish_date %><br>
    <%= f.date_select :estimated_finish_date, :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :before_comment %><br>
    <%= f.text_area :before_comment %>
  </div>
  <div class="actions">
    <%= f.submit  :value => t('views.buttun_repairStarted') %>
  </div>
  <%= link_to t('views.link_back'), repairs_path %>
</div>

  <div class="well col-md-8">
  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :disabled=> true %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.text_field :order_date, :disabled=> true %>
  </div>


<% if false %>
  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.text_field :order_no, :use_month_numbers => true, :disabled=> disabled_data[:order_no] %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.date_select :order_date, :use_month_numbers => true, :disabled=> disabled_data[:order_date] %>
  </div>
<% end %>


  <div class="field">
    <%= f.label :construction_no %><br>
    <%= f.text_field :construction_no, :disabled=> disabled_data[:construction_no] %>
  </div>
  <div class="field">
    <%= f.label :desirable_finish_date %><br>
    <%= f.date_select :desirable_finish_date, :use_month_numbers => true, :disabled=>disabled_data[:desirable_finish_date] %>
  </div>

  <div class="field">
    <%= label_tag 'コメント(交換理由)' %><br>
    <%= f.text_area :change_comment, :disabled=> true %>
  </div>

  </div>
</div>
<% end %>

app/views/repairs/show.html.erb
 <div class="field">
  <%= Engine.human_attribute_name('engine_model_name') %>：
    <%= @repair.engine.engine_model_name %>
  </div>

 <div class="field">
    <%= Engine.human_attribute_name('serialno') %>
    <%= @repair.engine.serialno %>
</div>


  <div class="field">
    <%= Repair.human_attribute_name('order_no') %>
    <%= @repair.order_no %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('order_date') %>
    <%= @repair.order_date %>
  </div>

  <div class="field">
    <%= Repair.human_attribute_name('arrive_date') %>
    <%=  @repair.arrive_date %>
  </div>


  <div class="field">
    <%= Repair.human_attribute_name('construction_no') %>
    <%= @repair.construction_no %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('desirable_finish_date') %>
    <%= @repair.desirable_finish_date %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('start_date') %>
    <%= @repair.start_date %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('estimated_finish_date') %>
    <%= @repair.estimated_finish_date %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('before_comment') %>
    <%= @repair.before_comment %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('finish_date') %>
    <%= @repair.finish_date %>
  </div>
  <div class="field">
    <%= Repair.human_attribute_name('after_comment') %>
    <%= @repair.after_comment %>
  </div>

<% if current_user.yesOffice? %>
  <%= link_to t('views.link_edit'), edit_repair_path(@repair) %> |
<% end %>

<%= link_to t('views.link_back'), repairs_path %>